version: '3.4'
services:
  dotnet:
    image: ${DOCKER_REGISTRY-}dotnet
    container_name: api
    build:
      context: .
      dockerfile: WebProject.api/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development

  blazor:
    image: ${DOCKER_REGISTRY-}blazor
    container_name: web
    build: 
      context: .
      dockerfile: WebProject.web/Dockerfile
    depends_on:
      - dotnet
    ports:
    - "4000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql:8.1.0
    container_name: mysqldb
    ports:
      - "3310:3306"
    expose: 
      - 3306
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: hw8vup5e
      MYSQL_USER: api
      MYSQL_PASSWORD: hw8vup5e
      MYSQL_DATABASE: api
volumes:
  db-volume:
